title: White Male Astronomer
description: A voice for the majority.

url: http://whitemaleastronomer.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   twitter: whitemaleastro
   email: whitemalescience@gmail.com

#google_analytics: "UA-58263416-1"
